name: 'Cloudflare Workers Preview'
description: 'Deploy Cloudflare workers preview for every pull request with Wrangler'
author: 'shidil'
inputs:
  cf_token:
    description: 'Cloudflare token (Edit Workers Scope)'
    required: true
  cf_account:
    description: 'Cloudflare account id'
    required: true
  domain:
    required: true
    description: 'eg.workers.dev'
  github_token:
    description: 'github token'
    required: true
  build:
    description: 'build scripts'
    default: |
      npm install
      npm run build
    required: false
  project_path:
    required: false
    description: 'directory of the wrangler project'
  failOnError:
    required: false
    description: 'Set `failed` if a deployment throws error'
  teardown:
    description: 'Determines if the preview instance will be torn down on PR close'
    default: 'false'
    required: false
outputs:
  preview_url:
    description: 'The url for the related PR preview'
runs:
  using: node12
  main: 'dist/index.js'
branding:
  icon: 'monitor'
  color: 'purple'
